version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouseDB
    ports:
      # HTTP interface
      - "8123:8123"
      # Native interface
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=formAnalytics
      - CLICKHOUSE_PASSWORD=test1234
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

  analytics-dashboard:
    image: analytics-dashboard
    container_name: analytics-dashboard
    network_mode: host
    restart: unless-stopped

  form-analytics:
    image: form-analytics
    container_name: form-analytics
    network_mode: host
    restart: unless-stopped

# To run: docker-compose up -d
# To connect to clickhouse: docker exec -it clickhouseDB clickhouse-client
# To stop: docker-compose stop
